### ISSUE TITLE
Length for tg_line?

### ISSUE THREAD

**Issue by simonrolfmore-brunswick** [tidwall/tg#5]
I absolutely appreciate this may not be the way you want to go with `tg`, but I figure it can't hurt to ask: would you be interested in exposing a function to calculate the length of a `tg_line`? 

It looks like there's already an internal `length` [function](https://github.com/tidwall/tg/blob/5c505b9d68470a30ea3efd52fcc437ed438d6a93/tg.c#L433) for calculating the Pythagoras distance between 2 points, and a [function](https://github.com/tidwall/tg/blob/5c505b9d68470a30ea3efd52fcc437ed438d6a93/tg.c#L13520) to calculate a ring's perimeter as part of the Polsby-Popper score calculation, so this doesn't appear to be a huge stretch in terms of extra code, but I understand this may not be an API overhead you want to take on.

For full disclosure, I'm asking for this with the hope of it getting incorporated into [`sqlite-tg`](https://github.com/asg017/sqlite-tg) as it's a much lighter-weight alternative to using Spatialite and the GeoJSON conversion, intersection, and bounding box functions are super useful for the work I'm doing.

**Comment by tidwall** [comment]
You're right that this should be a relatively simple change. Most of the code is already there but just needs to be exposed to the API.

I'll dig a little deep and see what I can do.

**Comment by tidwall** [comment]
The method is now available.

**Comment by simonrolfmore-brunswick** [comment]
Thank you! Looks fantastic :)
